# Where the site will be built.
destination: _site_aws

# This URL is the main address for absolute links. Don't include a slash at the end.
#
url: 'http://cla-public-backup.s3-website-us-east-1.amazonaws.com'
baseurl: '/'

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
#
# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)
#
urlimg: '/assets/images/'

# and audio:
#
urlaudio: '/assets/audio/'

# JSON source data for map.
clamap: http://cla-public-backup.s3-website-us-east-1.amazonaws.com//browse/cla-map.json

search:
  aws_endpoint: https://xcsocq3938.execute-api.us-east-1.amazonaws.com/awscloudfrontapi/
