# Where the site will be built.
destination: _site_local

# This URL is the main address for absolute links. Don't include a slash at the end.
#
url: 'http://localhost:4000'
baseurl: '/'

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
#
# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)
#
#urlimg: 'https://phlow.github.io/feeling-responsive/images/'
urlimg: '/images/'


# JSON source data for map.
clamap: https://linguistics.berkeley.edu/scoil_dev_cla_public/cla-map.json
